"""Generate the JSON Schema and its TypeScript projection from one source model."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from gridlock.models import Payload


def _type_from_schema(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(_type_from_schema(option) for option in schema["anyOf"])
    if schema.get("type") == "array":
        return f"Array<{_type_from_schema(schema.get('items', {}))}>"
    if schema.get("type") == "object":
        properties = schema.get("properties")
        if not properties:
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        fields = [
            f"{key}{'' if key in required else '?'}: {_type_from_schema(value)}"
            for key, value in properties.items()
        ]
        return "{ " + "; ".join(fields) + " }"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(schema.get("type"), "unknown")


def schema_to_typescript(schema: dict[str, Any]) -> str:
    """Convert the Pydantic-generated subset of JSON Schema used by this project."""
    declarations = ["// Generated by `gridlock contract export`. Do not edit manually.", ""]
    definitions = schema.get("$defs", {})
    for name, definition in definitions.items():
        if "enum" in definition:
            declarations.append(f"export type {name} = {_type_from_schema(definition)};")
            continue
        required = set(definition.get("required", []))
        declarations.append(f"export interface {name} {{")
        for key, property_schema in definition.get("properties", {}).items():
            optional = "" if key in required else "?"
            declarations.append(f"  {key}{optional}: {_type_from_schema(property_schema)};")
        declarations.append("}")
    root_type = _type_from_schema({"$ref": "#/$defs/Payload"})
    declarations.extend(["", f"export type GridlockPayload = {root_type};", ""])
    return "\n".join(declarations)


def export_contract(repository_root: Path) -> tuple[Path, Path]:
    """Write canonical API schema and derived frontend types in a stable order."""
    schema = Payload.model_json_schema(by_alias=True)
    schema_path = repository_root / "contract" / "gridlock.schema.json"
    types_path = repository_root / "frontend" / "src" / "lib" / "contract.ts"
    schema_path.parent.mkdir(parents=True, exist_ok=True)
    types_path.parent.mkdir(parents=True, exist_ok=True)
    schema_path.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    types_path.write_text(schema_to_typescript(schema), encoding="utf-8")
    return schema_path, types_path

